[versions]
# libraries
annotations = "24.1.0"
lombokGradlePlugin = "8.4"
okHttp = "4.12.0"

# plugins
kotlin = "1.9.21"
changelog = "2.2.0"
gradleIntelliJPlugin = "1.16.1"
qodana = "0.1.13"
kover = "0.7.6"
jackson = "2.16.1"

[libraries]
annotations = { group = "org.jetbrains", name = "annotations", version.ref = "annotations" }
jackson-datatype-jdk8 = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jdk8", version.ref = "jackson" }
jackson-datatype-jsr310 = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jsr310", version.ref = "jackson" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okHttp"}
okhttp-sse = { module = "com.squareup.okhttp3:okhttp-sse", version.ref = "okHttp" }

[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
gradleIntelliJPlugin = { id = "org.jetbrains.intellij", version.ref = "gradleIntelliJPlugin" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
qodana = { id = "org.jetbrains.qodana", version.ref = "qodana" }
lombok = { id = "io.freefair.lombok", version.ref = "lombokGradlePlugin" }

[bundles]
# Define bundles/groups of libraries
jacksonDatatype = ["jackson-datatype-jdk8", "jackson-datatype-jsr310"]
okHttp = ["okhttp", "okhttp-sse"]